/**
 * Downloads the Matthew Proctor Australian postcodes dataset and generates
 * src/data/waPostcodes.ts with every WA postcode → [lat, lng].
 *
 * Usage: npx tsx scripts/buildWAPostcodes.ts
 */

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const CSV_URL =
  "https://raw.githubusercontent.com/matthewproctor/australianpostcodes/master/australian_postcodes.csv";

async function main() {
  console.log("Downloading Australian postcodes dataset…");
  const res = await fetch(CSV_URL);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const csv = await res.text();

  const lines = csv.split("\n");
  const header = lines[0].split(",").map((h) => h.trim().replace(/^"|"$/g, ""));

  const idxPostcode = header.indexOf("postcode");
  const idxState = header.indexOf("state");
  const idxLat = header.indexOf("lat");
  const idxLng = header.indexOf("long");
  const idxLocality = header.indexOf("locality");

  if ([idxPostcode, idxState, idxLat, idxLng].some((i) => i === -1)) {
    throw new Error(`Missing expected columns. Found: ${header.join(", ")}`);
  }

  // Group by postcode, accumulate lat/lng to average them (some postcodes
  // span multiple localities with separate rows)
  const map = new Map<string, { lats: number[]; lngs: number[]; locality: string }>();
  // All locality → postcode pairs for the suburb search index
  const suburbPairs: Array<{ name: string; postcode: string }> = [];
  const seenSuburb = new Set<string>();

  for (let i = 1; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;

    // Simple CSV split — fields may be quoted
    const cols = line.split(",").map((c) => c.replace(/^"|"$/g, "").trim());

    const state = cols[idxState];
    if (state !== "WA") continue;

    const postcode = cols[idxPostcode];
    if (!postcode || !/^\d{4}$/.test(postcode)) continue;

    const lat = parseFloat(cols[idxLat]);
    const lng = parseFloat(cols[idxLng]);
    if (!lat || !lng || isNaN(lat) || isNaN(lng)) continue;
    // Skip clearly invalid coords (sometimes dataset has 0,0 placeholders)
    if (Math.abs(lat) < 5 || Math.abs(lng) < 100) continue;

    const locality = cols[idxLocality] ?? "";
    if (!map.has(postcode)) {
      map.set(postcode, { lats: [], lngs: [], locality });
    }
    const entry = map.get(postcode)!;
    entry.lats.push(lat);
    entry.lngs.push(lng);

    // Collect unique locality → postcode pairs for suburb search
    if (locality) {
      const key = `${locality}|${postcode}`;
      if (!seenSuburb.has(key)) {
        seenSuburb.add(key);
        suburbPairs.push({ name: locality, postcode });
      }
    }
  }

  const sorted = [...map.entries()].sort(([a], [b]) => a.localeCompare(b));

  const lines2 = sorted.map(([postcode, { lats, lngs, locality }]) => {
    const lat = (lats.reduce((s, v) => s + v, 0) / lats.length).toFixed(4);
    const lng = (lngs.reduce((s, v) => s + v, 0) / lngs.length).toFixed(4);
    const comment = locality ? ` // ${locality}` : "";
    return `  "${postcode}": [${lat}, ${lng}],${comment}`;
  });

  suburbPairs.sort((a, b) => a.name.localeCompare(b.name));
  const suburbLines = suburbPairs.map(
    ({ name, postcode }) => `  { name: ${JSON.stringify(name)}, postcode: "${postcode}", state: "WA" },`
  );

  const output = `// Auto-generated by scripts/buildWAPostcodes.ts — do not edit manually.
// Source: https://github.com/matthewproctor/australianpostcodes
// ${sorted.length} WA postcodes with averaged lat/lng per postcode.
export const WA_POSTCODE_COORDS: Record<string, [number, number]> = {
${lines2.join("\n")}
};

// All WA locality names with their postcode — used for suburb search autocomplete.
export const WA_SUBURB_INDEX: Array<{ name: string; postcode: string; state: string }> = [
${suburbLines.join("\n")}
];
`;

  const outPath = join(__dirname, "../src/data/waPostcodes.ts");
  writeFileSync(outPath, output, "utf8");
  console.log(`✓ Written ${sorted.length} postcodes → src/data/waPostcodes.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
